name: Build Docs

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'src/**'  # Only trigger on changes in the docs folder
      - 'public/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # or your preferred Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build docs
      run: npm run build

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Automated docs build" || echo "No changes to commit"
        git push
